In [27]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [28]:
data = pd.read_csv('C:/Users/MANISH GOLA/Downloads/student-mat.csv')

In [29]:
data.head(20)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0      GP   F   18       U     GT3       A     4     4   at_home   teacher   
1      GP   F   17       U     GT3       T     1     1   at_home     other   
2      GP   F   15       U     LE3       T     1     1   at_home     other   
3      GP   F   15       U     GT3       T     4     2    health  services   
4      GP   F   16       U     GT3       T     3     3     other     other   
5      GP   M   16       U     LE3       T     4     3  services     other   
6      GP   M   16       U     LE3       T     2     2     other     other   
7      GP   F   17       U     GT3       A     4     4     other   teacher   
8      GP   M   15       U     LE3       A     3     2  services     other   
9      GP   M   15       U     GT3       T     3     4     other     other   
10     GP   F   15       U     GT3       T     4     4   teacher    health   
11     GP   F   15       U     GT3       T     2     1  services     other   
12     GP   M   15       U     LE3       T     4     4    health  services   
13     GP   M   15       U     GT3       T     4     3   teacher     other   
14     GP   M   15       U     GT3       A     2     2     other     other   
15     GP   F   16       U     GT3       T     4     4    health     other   
16     GP   F   16       U     GT3       T     4     4  services  services   
17     GP   F   16       U     GT3       T     3     3     other     other   
18     GP   M   17       U     GT3       T     3     2  services  services   
19     GP   M   16       U     LE3       T     4     3    health     other   

    ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0   ...      4        3      4     1     1      3        6   5   6   6  
1   ...      5        3      3     1     1      3        4   5   5   6  
2   ...      4        3      2     2     3      3       10   7   8  10  
3   ...      3        2      2     1     1      5        2  15  14  15  
4   ...      4        3      2     1     2      5        4   6  10  10  
5   ...      5        4      2     1     2      5       10  15  15  15  
6   ...      4        4      4     1     1      3        0  12  12  11  
7   ...      4        1      4     1     1      1        6   6   5   6  
8   ...      4        2      2     1     1      1        0  16  18  19  
9   ...      5        5      1     1     1      5        0  14  15  15  
10  ...      3        3      3     1     2      2        0  10   8   9  
11  ...      5        2      2     1     1      4        4  10  12  12  
12  ...      4        3      3     1     3      5        2  14  14  14  
13  ...      5        4      3     1     2      3        2  10  10  11  
14  ...      4        5      2     1     1      3        0  14  16  16  
15  ...      4        4      4     1     2      2        4  14  14  14  
16  ...      3        2      3     1     2      2        6  13  14  14  
17  ...      5        3      2     1     1      4        4   8  10  10  
18  ...      5        5      5     2     4      5       16   6   5   5  
19  ...      3        1      3     1     3      5        4   8  10  10  

[20 rows x 33 columns]

In [30]:
data.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

In [37]:
data.isnull().values.any()

False

In [10]:
data.shape

(395, 33)

In [38]:
data.columns

Index(['G1', 'G2', 'G3', 'studytime', 'failures', 'absences'], dtype='object')

In [39]:
data.nunique()

G1           17
G2           17
G3           18
studytime     4
failures      4
absences     34
dtype: int64

In [40]:
data['GAvg'] = (data['G1'] + data['G2'] + data['G3']) / 3

In [41]:
def define_grade(df):
    # Create a list to store the data
    grades = []

    # For each row in the column,
    for row in df['GAvg']:
        # if more than a value,
        if row >= (0.9 * df['GAvg'].max()):
            # Append a letter grade
            grades.append('A')
        # else, if more than a value,
        elif row >= (0.7 * df['GAvg'].max()):
            # Append a letter grade
            grades.append('B')
        # else, if more than a value,
        elif row < (0.7 * df['GAvg'].max()):
            # Append a letter grade
            grades.append('C')   
    # Create a column from the list
    df['grades'] = grades
    return df

In [42]:
data = define_grade(data)
data.head()

G1  G2  G3  studytime  failures  absences       GAvg grades
0   5   6   6          2         0         6   5.666667      C
1   5   5   6          2         0         4   5.333333      C
2   7   8  10          2         3        10   8.333333      C
3  15  14  15          3         0         2  14.666667      B
4   6  10  10          2         0         4   8.666667      C

In [46]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7951508385643893


In [47]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 8.55641514 11.34185393 15.18006868  9.14928645 11.34185393]
 [ 8.55641514  8.55641514 15.18006868  9.14928645  9.27622022]
 [11.85665546  9.25018133 15.18006868 16.38332671 12.91264522]
 ...
 [12.91264522  9.25018133 13.11015959 16.38332671 16.38332671]
 [ 9.57104898 12.85310627 13.11015959  9.14928645  9.14928645]
 [ 9.25018133 15.23960763 13.11015959  9.14928645  8.55641514]] [[[ 9  9  2  0  8]
  [10 12  2  1  4]
  [15 15  2  0  2]
  [ 7 10  2  0  6]
  [10 12  2  1  4]]

 [[ 9  9  2  0  8]
  [ 9  9  2  0  8]
  [15 15  2  0  2]
  [ 7 10  2  0  6]
  [10 10  2  1  0]]

 [[11 12  2  0 10]
  [ 8 10  2  0  4]
  [15 15  2  0  2]
  [16 16  1  0  0]
  [13 13  2  0  2]]

 ...

 [[13 13  2  0  2]
  [ 8 10  2  0  4]
  [15 13  3  2 14]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[10 10  2  0  4]
  [13 13  2  0  0]
  [15 13  3  2 14]
  [ 7 10  2  0  6]
  [ 7 10  2  0  6]]

 [[ 8 10  2  0  4]
  [15 15  2  0  4]
  [15 13  3  2 14]
  [ 7 10  2  0  6]
  [ 9  9  2  0  8]]] [array([[ 9, 12, 16, 10, 12]